<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FELICIA_8FEL1806UTAMAYBS_DAPAT_MELAKU_0f6e6f</name>
   <tag></tag>
   <elementGuidId>49924dc2-75e9-452f-bc2e-d73c45b93e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='8|FEL1806|UTAMA|YBS_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8|FEL1806|UTAMA|YBS_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>8|FEL1806|UTAMA|YBS_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div7&quot;)/table[1]/tbody[1]/tr[3]/td[6]/input[@id=&quot;8|FEL1806|UTAMA|YBS_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='8|FEL1806|UTAMA|YBS_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div7']/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
