<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANGGIE PUSPA ANGGRAENI MARGIONO_1AMG1_091c92</name>
   <tag></tag>
   <elementGuidId>fbe497a0-1c4e-4d22-8292-4297dffedd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='1|AMG1414|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1|AMG1414|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1|AMG1414|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div0&quot;)/table[1]/tbody[1]/tr[2]/td[4]/input[@id=&quot;1|AMG1414|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='1|AMG1414|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div0']/table/tbody/tr[2]/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
