<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AZKA FADHLAN_11AFD1193UTAMAKEBERADAAN_d0c169</name>
   <tag></tag>
   <elementGuidId>783dedba-ce88-4014-9236-993d5ed103ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='11|AFD1193|UTAMA|KEBERADAAN_YBS_MEMBERIKAN_WARNA_YANG_POSITIF_DALAM_KELOMPOK'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11|AFD1193|UTAMA|KEBERADAAN_YBS_MEMBERIKAN_WARNA_YANG_POSITIF_DALAM_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11|AFD1193|UTAMA|KEBERADAAN_YBS_MEMBERIKAN_WARNA_YANG_POSITIF_DALAM_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div10&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;11|AFD1193|UTAMA|KEBERADAAN_YBS_MEMBERIKAN_WARNA_YANG_POSITIF_DALAM_KELOMPOK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='11|AFD1193|UTAMA|KEBERADAAN_YBS_MEMBERIKAN_WARNA_YANG_POSITIF_DALAM_KELOMPOK'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div10']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
