<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FELICIA_17FEL1806UTAMAYBS_MEMBUAT_REN_3f49d6</name>
   <tag></tag>
   <elementGuidId>1a9ec4bb-71ed-461f-b930-7449acf278ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='17|FEL1806|UTAMA|YBS_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17|FEL1806|UTAMA|YBS_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>17|FEL1806|UTAMA|YBS_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div16&quot;)/table[1]/tbody[1]/tr[3]/td[6]/input[@id=&quot;17|FEL1806|UTAMA|YBS_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='17|FEL1806|UTAMA|YBS_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div16']/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
