<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANGGIE PUSPA ANGGRAENI MARGIONO_4AMG1_3c3dd7</name>
   <tag></tag>
   <elementGuidId>e9277cb4-fa2e-4243-8782-bc80f79ac82d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='4|AMG1414|UTAMA|YBS_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4|AMG1414|UTAMA|YBS_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>4|AMG1414|UTAMA|YBS_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div3&quot;)/table[1]/tbody[1]/tr[2]/td[6]/input[@id=&quot;4|AMG1414|UTAMA|YBS_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='4|AMG1414|UTAMA|YBS_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div3']/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
