<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AZKA FADHLAN_9AFD1193UTAMAYBS_MENUNJU_35df31</name>
   <tag></tag>
   <elementGuidId>67ca1fa5-0313-4c40-b1dd-24d5f75d5189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='9|AFD1193|UTAMA|YBS_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9|AFD1193|UTAMA|YBS_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>9|AFD1193|UTAMA|YBS_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div8&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;9|AFD1193|UTAMA|YBS_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='9|AFD1193|UTAMA|YBS_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div8']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
