<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANGGIE PUSPA ANGGRAENI MARGIONO_2AMG1_85d781</name>
   <tag></tag>
   <elementGuidId>3629c126-0c34-4023-b0bb-fa4858da45be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='2|AMG1414|UTAMA|YBS_BEKERJA_SESUAI_DENGAN_PDCA_(PLAN_-_DO_-_CHECK_-_ACTION)'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2|AMG1414|UTAMA|YBS_BEKERJA_SESUAI_DENGAN_PDCA_(PLAN_-_DO_-_CHECK_-_ACTION)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2|AMG1414|UTAMA|YBS_BEKERJA_SESUAI_DENGAN_PDCA_(PLAN_-_DO_-_CHECK_-_ACTION)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div1&quot;)/table[1]/tbody[1]/tr[2]/td[6]/input[@id=&quot;2|AMG1414|UTAMA|YBS_BEKERJA_SESUAI_DENGAN_PDCA_(PLAN_-_DO_-_CHECK_-_ACTION)&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='2|AMG1414|UTAMA|YBS_BEKERJA_SESUAI_DENGAN_PDCA_(PLAN_-_DO_-_CHECK_-_ACTION)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div1']/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
