<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_10SNG0014UTAMAYBS_D_f3851c</name>
   <tag></tag>
   <elementGuidId>c0df0bac-2071-4718-bd2e-faf99893d970</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='10|SNG0014|UTAMA|YBS_DAPAT_MENCIPTAKAN_SINERGI_YANG_POSITIF__DALAM_KELOMPOK_'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10|SNG0014|UTAMA|YBS_DAPAT_MENCIPTAKAN_SINERGI_YANG_POSITIF__DALAM_KELOMPOK_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>10|SNG0014|UTAMA|YBS_DAPAT_MENCIPTAKAN_SINERGI_YANG_POSITIF__DALAM_KELOMPOK_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div9&quot;)/table[1]/tbody[1]/tr[6]/td[6]/input[@id=&quot;10|SNG0014|UTAMA|YBS_DAPAT_MENCIPTAKAN_SINERGI_YANG_POSITIF__DALAM_KELOMPOK_&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='10|SNG0014|UTAMA|YBS_DAPAT_MENCIPTAKAN_SINERGI_YANG_POSITIF__DALAM_KELOMPOK_'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div9']/table/tbody/tr[6]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/table/tbody/tr[6]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
