<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PRIHATINI SANDYA PUTRIE_5PSP0399UTAMA_8c9807</name>
   <tag></tag>
   <elementGuidId>6102a390-8b11-46a2-b2f4-75d96514c66e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='5|PSP0399|UTAMA|YBS_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5|PSP0399|UTAMA|YBS_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>5|PSP0399|UTAMA|YBS_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div4&quot;)/table[1]/tbody[1]/tr[5]/td[6]/input[@id=&quot;5|PSP0399|UTAMA|YBS_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='5|PSP0399|UTAMA|YBS_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div4']/table/tbody/tr[5]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr[5]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
