<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANGGIE PUSPA ANGGRAENI MARGIONO_3AMG1_b5461a</name>
   <tag></tag>
   <elementGuidId>fd8b1012-160b-4bd9-a2b7-814f0f9bfb84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='3|AMG1414|UTAMA|YBS_BERTANGGUNG_JAWAB_TERHADAP_HASIL_KERJA_PRIBADI_&amp;_TIM_'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3|AMG1414|UTAMA|YBS_BERTANGGUNG_JAWAB_TERHADAP_HASIL_KERJA_PRIBADI_&amp;_TIM_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>3|AMG1414|UTAMA|YBS_BERTANGGUNG_JAWAB_TERHADAP_HASIL_KERJA_PRIBADI_&amp;_TIM_</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div2&quot;)/table[1]/tbody[1]/tr[2]/td[6]/input[@id=&quot;3|AMG1414|UTAMA|YBS_BERTANGGUNG_JAWAB_TERHADAP_HASIL_KERJA_PRIBADI_&amp;_TIM_&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='3|AMG1414|UTAMA|YBS_BERTANGGUNG_JAWAB_TERHADAP_HASIL_KERJA_PRIBADI_&amp;_TIM_'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div2']/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
