<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AZKA FADHLAN_15AFD1193UTAMAYBS_MEMILI_8c91b3</name>
   <tag></tag>
   <elementGuidId>999b8323-a77d-41fe-a01c-f194812f0bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='15|AFD1193|UTAMA|YBS_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>15|AFD1193|UTAMA|YBS_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>15|AFD1193|UTAMA|YBS_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div14&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;15|AFD1193|UTAMA|YBS_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='15|AFD1193|UTAMA|YBS_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div14']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
