<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ANGGIE PUSPA ANGGRAENI MARGIONO_14AMG_3af7a7</name>
   <tag></tag>
   <elementGuidId>f8373f4d-1a89-41d5-9bc4-8b3323c448e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='14|AMG1414|UTAMA|YBS_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14|AMG1414|UTAMA|YBS_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>14|AMG1414|UTAMA|YBS_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div13&quot;)/table[1]/tbody[1]/tr[2]/td[6]/input[@id=&quot;14|AMG1414|UTAMA|YBS_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='14|AMG1414|UTAMA|YBS_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div13']/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/table/tbody/tr[2]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
