<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FELICIA_19FEL1806UTAMAYBS_BERUSAHA_ME_f66537</name>
   <tag></tag>
   <elementGuidId>6b9ac89b-30cd-4046-bff4-7fd2b0abda93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='19|FEL1806|UTAMA|YBS_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>19|FEL1806|UTAMA|YBS_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>19|FEL1806|UTAMA|YBS_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div18&quot;)/table[1]/tbody[1]/tr[3]/td[6]/input[@id=&quot;19|FEL1806|UTAMA|YBS_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='19|FEL1806|UTAMA|YBS_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div18']/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/table/tbody/tr[3]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
