<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_HENDRY SAGITA_22HSG2275ESSAYTULISK_ffaf88</name>
   <tag></tag>
   <elementGuidId>83b7006e-81ac-46ff-af28-6f32bc37ba85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='22|HSG2275|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_REKAN_KERJA:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>22|HSG2275|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_REKAN_KERJA:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>22|HSG2275|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_REKAN_KERJA:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;22|HSG2275|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_REKAN_KERJA:&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='22|HSG2275|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_REKAN_KERJA:']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div21']/table/tbody/tr[4]/td[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/textarea</value>
   </webElementXpaths>
</WebElementEntity>
