<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_19KEG2200UTAMASAYA_MEL_0dcf6a</name>
   <tag></tag>
   <elementGuidId>1842ec0f-cfc2-4c7b-a33f-24092f45f194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='19|KEG2200|UTAMA|SAYA_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>19|KEG2200|UTAMA|SAYA_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>19|KEG2200|UTAMA|SAYA_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div18&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;19|KEG2200|UTAMA|SAYA_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='19|KEG2200|UTAMA|SAYA_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div18']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
