<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_7KEG2200UTAMASAYA_DAPA_1c3a5c</name>
   <tag></tag>
   <elementGuidId>50eca7a0-9d67-4b1c-a2fc-e8d7f0b2479a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='7|KEG2200|UTAMA|SAYA_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>7|KEG2200|UTAMA|SAYA_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>7|KEG2200|UTAMA|SAYA_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div6&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;7|KEG2200|UTAMA|SAYA_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='7|KEG2200|UTAMA|SAYA_DAPAT_MELAKUKAN_KOORDINASI_BAIK_DAN_BEKERJA_SAMA_DENGAN_SEMUA_PIHAK'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div6']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
