<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_16KEG2200UTAMASAYA_MEM_f16952</name>
   <tag></tag>
   <elementGuidId>13a7f2d4-dd4f-416c-bf27-c4127765957c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='16|KEG2200|UTAMA|SAYA_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>16|KEG2200|UTAMA|SAYA_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>16|KEG2200|UTAMA|SAYA_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div15&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;16|KEG2200|UTAMA|SAYA_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='16|KEG2200|UTAMA|SAYA_MEMBUAT_RENCANA_KERJA_DENGAN_BERORIENTASI_KEBUTUHAN_CUSTOMER_(END_CUSTOMER/NEXT_PROCESS)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div15']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
