<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_11KEG2200UTAMASAYA_TID_af2862</name>
   <tag></tag>
   <elementGuidId>8381beb8-b982-4cb7-b387-62f95ef77c02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='11|KEG2200|UTAMA|SAYA_TIDAK_PUAS_DENGAN_HASIL_KERJA_YANG_BIASA-BIASA_SAJA'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>11|KEG2200|UTAMA|SAYA_TIDAK_PUAS_DENGAN_HASIL_KERJA_YANG_BIASA-BIASA_SAJA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>11|KEG2200|UTAMA|SAYA_TIDAK_PUAS_DENGAN_HASIL_KERJA_YANG_BIASA-BIASA_SAJA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div10&quot;)/table[1]/tbody[1]/tr[1]/td[4]/input[@id=&quot;11|KEG2200|UTAMA|SAYA_TIDAK_PUAS_DENGAN_HASIL_KERJA_YANG_BIASA-BIASA_SAJA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='11|KEG2200|UTAMA|SAYA_TIDAK_PUAS_DENGAN_HASIL_KERJA_YANG_BIASA-BIASA_SAJA'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div10']/table/tbody/tr/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/table/tbody/tr/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
