<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_12KEG2200UTAMASAYA_MEM_4e6179</name>
   <tag></tag>
   <elementGuidId>1d2c68a2-264b-4f85-a48d-f09448b7e81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='12|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>12|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>12|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div11&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;12|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='12|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div11']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
