<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_17KEG2200UTAMASAYA_PRO_8aaf72</name>
   <tag></tag>
   <elementGuidId>b7ddf0d8-9155-49af-af69-bc268f7ebc37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='17|KEG2200|UTAMA|SAYA_PROAKTIF_DAN_CEPAT_TANGGAP_DALAM_MERESPON/MENYELESAIKAN_SEGALA_KEBUTUHAN_CUSTOMER__HINGGA_TUNTAS'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17|KEG2200|UTAMA|SAYA_PROAKTIF_DAN_CEPAT_TANGGAP_DALAM_MERESPON/MENYELESAIKAN_SEGALA_KEBUTUHAN_CUSTOMER__HINGGA_TUNTAS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>17|KEG2200|UTAMA|SAYA_PROAKTIF_DAN_CEPAT_TANGGAP_DALAM_MERESPON/MENYELESAIKAN_SEGALA_KEBUTUHAN_CUSTOMER__HINGGA_TUNTAS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div16&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;17|KEG2200|UTAMA|SAYA_PROAKTIF_DAN_CEPAT_TANGGAP_DALAM_MERESPON/MENYELESAIKAN_SEGALA_KEBUTUHAN_CUSTOMER__HINGGA_TUNTAS&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='17|KEG2200|UTAMA|SAYA_PROAKTIF_DAN_CEPAT_TANGGAP_DALAM_MERESPON/MENYELESAIKAN_SEGALA_KEBUTUHAN_CUSTOMER__HINGGA_TUNTAS'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div16']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
