<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_10SNG0014UTAMAYBS_M_8d1155</name>
   <tag></tag>
   <elementGuidId>20c1d979-5648-4b57-a3c6-1c18c5ba6b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='10|SNG0014|UTAMA|YBS_MENYAMPAIKAN_TUJUAN_ATAU_GOAL_YANG_JELAS_DAN_SPESIFIK_ATAS_PEKERJAAN_YANG_DIBERIKANNYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>10|SNG0014|UTAMA|YBS_MENYAMPAIKAN_TUJUAN_ATAU_GOAL_YANG_JELAS_DAN_SPESIFIK_ATAS_PEKERJAAN_YANG_DIBERIKANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>10|SNG0014|UTAMA|YBS_MENYAMPAIKAN_TUJUAN_ATAU_GOAL_YANG_JELAS_DAN_SPESIFIK_ATAS_PEKERJAAN_YANG_DIBERIKANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div9&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;10|SNG0014|UTAMA|YBS_MENYAMPAIKAN_TUJUAN_ATAU_GOAL_YANG_JELAS_DAN_SPESIFIK_ATAS_PEKERJAAN_YANG_DIBERIKANNYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='10|SNG0014|UTAMA|YBS_MENYAMPAIKAN_TUJUAN_ATAU_GOAL_YANG_JELAS_DAN_SPESIFIK_ATAS_PEKERJAAN_YANG_DIBERIKANNYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div9']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
