<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_2SNG0014UTAMAYBS_ME_ee81a5</name>
   <tag></tag>
   <elementGuidId>e2980ecb-c0c4-435e-8f69-80c13e5dad0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='2|SNG0014|UTAMA|YBS_MEMBANGUN_SUASANA_KERJA_POSITIF_DAN_SEMANGAT_KERJA_SAMA_DI_ANTARA_ANGGOTA_TIM_UNTUK_MENCAPAI_TARGET_YANG_TELAH_DITETAPKAN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2|SNG0014|UTAMA|YBS_MEMBANGUN_SUASANA_KERJA_POSITIF_DAN_SEMANGAT_KERJA_SAMA_DI_ANTARA_ANGGOTA_TIM_UNTUK_MENCAPAI_TARGET_YANG_TELAH_DITETAPKAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2|SNG0014|UTAMA|YBS_MEMBANGUN_SUASANA_KERJA_POSITIF_DAN_SEMANGAT_KERJA_SAMA_DI_ANTARA_ANGGOTA_TIM_UNTUK_MENCAPAI_TARGET_YANG_TELAH_DITETAPKAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div1&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;2|SNG0014|UTAMA|YBS_MEMBANGUN_SUASANA_KERJA_POSITIF_DAN_SEMANGAT_KERJA_SAMA_DI_ANTARA_ANGGOTA_TIM_UNTUK_MENCAPAI_TARGET_YANG_TELAH_DITETAPKAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='2|SNG0014|UTAMA|YBS_MEMBANGUN_SUASANA_KERJA_POSITIF_DAN_SEMANGAT_KERJA_SAMA_DI_ANTARA_ANGGOTA_TIM_UNTUK_MENCAPAI_TARGET_YANG_TELAH_DITETAPKAN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div1']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
