<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_18SNG0014UTAMAYBS_R_d9e22e</name>
   <tag></tag>
   <elementGuidId>3c785bbb-77ed-486c-8afd-1568334a4839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='18|SNG0014|UTAMA|YBS_REGULAR_MEMBUAT_IDP_(INDIVIDUAL_PENGEMBANGAN_PLAN)_UNTUK_SETIAP_ANGGOTA_TIM_NYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>18|SNG0014|UTAMA|YBS_REGULAR_MEMBUAT_IDP_(INDIVIDUAL_PENGEMBANGAN_PLAN)_UNTUK_SETIAP_ANGGOTA_TIM_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>18|SNG0014|UTAMA|YBS_REGULAR_MEMBUAT_IDP_(INDIVIDUAL_PENGEMBANGAN_PLAN)_UNTUK_SETIAP_ANGGOTA_TIM_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div17&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;18|SNG0014|UTAMA|YBS_REGULAR_MEMBUAT_IDP_(INDIVIDUAL_PENGEMBANGAN_PLAN)_UNTUK_SETIAP_ANGGOTA_TIM_NYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='18|SNG0014|UTAMA|YBS_REGULAR_MEMBUAT_IDP_(INDIVIDUAL_PENGEMBANGAN_PLAN)_UNTUK_SETIAP_ANGGOTA_TIM_NYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div17']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
