<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_16SNG0014UTAMAYBS_M_6abccd</name>
   <tag></tag>
   <elementGuidId>dc8ede94-c0c3-4920-807c-c4067501b27b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='16|SNG0014|UTAMA|YBS_MELAKUKAN_EVALUASI_YANG_OBYEKTIF_TERHADAP_PENCAPAIAN_RENCANA_KERJA_DAN_TARGET_DARI_MASING2_TIM/BAWAHAN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>16|SNG0014|UTAMA|YBS_MELAKUKAN_EVALUASI_YANG_OBYEKTIF_TERHADAP_PENCAPAIAN_RENCANA_KERJA_DAN_TARGET_DARI_MASING2_TIM/BAWAHAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>16|SNG0014|UTAMA|YBS_MELAKUKAN_EVALUASI_YANG_OBYEKTIF_TERHADAP_PENCAPAIAN_RENCANA_KERJA_DAN_TARGET_DARI_MASING2_TIM/BAWAHAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div15&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;16|SNG0014|UTAMA|YBS_MELAKUKAN_EVALUASI_YANG_OBYEKTIF_TERHADAP_PENCAPAIAN_RENCANA_KERJA_DAN_TARGET_DARI_MASING2_TIM/BAWAHAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='16|SNG0014|UTAMA|YBS_MELAKUKAN_EVALUASI_YANG_OBYEKTIF_TERHADAP_PENCAPAIAN_RENCANA_KERJA_DAN_TARGET_DARI_MASING2_TIM/BAWAHAN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div15']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
