<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_13SNG0014UTAMAYBS_B_a72ae7</name>
   <tag></tag>
   <elementGuidId>6ac97455-7c5b-455a-b375-f2a33557823d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='13|SNG0014|UTAMA|YBS_BISA_MENJADI_PARTNER_DISKUSI_BAGI_TEAM_NYA_DALAM_MENEMUKAN_SOLUSI_ATAS_PERMASALAHAN_YANG_MUNCUL'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13|SNG0014|UTAMA|YBS_BISA_MENJADI_PARTNER_DISKUSI_BAGI_TEAM_NYA_DALAM_MENEMUKAN_SOLUSI_ATAS_PERMASALAHAN_YANG_MUNCUL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>13|SNG0014|UTAMA|YBS_BISA_MENJADI_PARTNER_DISKUSI_BAGI_TEAM_NYA_DALAM_MENEMUKAN_SOLUSI_ATAS_PERMASALAHAN_YANG_MUNCUL</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div12&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;13|SNG0014|UTAMA|YBS_BISA_MENJADI_PARTNER_DISKUSI_BAGI_TEAM_NYA_DALAM_MENEMUKAN_SOLUSI_ATAS_PERMASALAHAN_YANG_MUNCUL&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='13|SNG0014|UTAMA|YBS_BISA_MENJADI_PARTNER_DISKUSI_BAGI_TEAM_NYA_DALAM_MENEMUKAN_SOLUSI_ATAS_PERMASALAHAN_YANG_MUNCUL'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div12']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
