<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_15SNG0014UTAMATIMBA_a5d68d</name>
   <tag></tag>
   <elementGuidId>0e125d41-31d5-4b36-8b74-28f0e7054198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='15|SNG0014|UTAMA|TIM/BAWAHAN_TERBUKA_UNTUK_MENYAMPAIKAN_KELUH_KESAH_/PERMASALAHAN_ATAS_PEKERJAANYA_(BAIK_FORMAL_MAUPUN_INFORMAL)'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>15|SNG0014|UTAMA|TIM/BAWAHAN_TERBUKA_UNTUK_MENYAMPAIKAN_KELUH_KESAH_/PERMASALAHAN_ATAS_PEKERJAANYA_(BAIK_FORMAL_MAUPUN_INFORMAL)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>15|SNG0014|UTAMA|TIM/BAWAHAN_TERBUKA_UNTUK_MENYAMPAIKAN_KELUH_KESAH_/PERMASALAHAN_ATAS_PEKERJAANYA_(BAIK_FORMAL_MAUPUN_INFORMAL)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div14&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;15|SNG0014|UTAMA|TIM/BAWAHAN_TERBUKA_UNTUK_MENYAMPAIKAN_KELUH_KESAH_/PERMASALAHAN_ATAS_PEKERJAANYA_(BAIK_FORMAL_MAUPUN_INFORMAL)&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='15|SNG0014|UTAMA|TIM/BAWAHAN_TERBUKA_UNTUK_MENYAMPAIKAN_KELUH_KESAH_/PERMASALAHAN_ATAS_PEKERJAANYA_(BAIK_FORMAL_MAUPUN_INFORMAL)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div14']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
