<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_5SNG0014UTAMAYBS_ME_a99889</name>
   <tag></tag>
   <elementGuidId>07420615-3fcc-435d-bba1-9b93af46115e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='5|SNG0014|UTAMA|YBS_MEMBANGUN_KOMUNIKASI_REGULAR_(FORMAL_DAN_INFORMAL)_DENGAN_ATASAN_-_BAWAHAN_DAN_REKAN_KERJA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>5|SNG0014|UTAMA|YBS_MEMBANGUN_KOMUNIKASI_REGULAR_(FORMAL_DAN_INFORMAL)_DENGAN_ATASAN_-_BAWAHAN_DAN_REKAN_KERJA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>5|SNG0014|UTAMA|YBS_MEMBANGUN_KOMUNIKASI_REGULAR_(FORMAL_DAN_INFORMAL)_DENGAN_ATASAN_-_BAWAHAN_DAN_REKAN_KERJA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div4&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;5|SNG0014|UTAMA|YBS_MEMBANGUN_KOMUNIKASI_REGULAR_(FORMAL_DAN_INFORMAL)_DENGAN_ATASAN_-_BAWAHAN_DAN_REKAN_KERJA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='5|SNG0014|UTAMA|YBS_MEMBANGUN_KOMUNIKASI_REGULAR_(FORMAL_DAN_INFORMAL)_DENGAN_ATASAN_-_BAWAHAN_DAN_REKAN_KERJA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div4']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
