<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_17SNG0014UTAMAYBS_D_e75c02</name>
   <tag></tag>
   <elementGuidId>699b20a9-76d8-4868-9433-2c694c20c8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='17|SNG0014|UTAMA|YBS_DAPAT_MENGIDENTIFIKASI_KEKUATAN_DAN_KELEMAHAN_ANGGOTA_TIM/BAWAHAN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17|SNG0014|UTAMA|YBS_DAPAT_MENGIDENTIFIKASI_KEKUATAN_DAN_KELEMAHAN_ANGGOTA_TIM/BAWAHAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>17|SNG0014|UTAMA|YBS_DAPAT_MENGIDENTIFIKASI_KEKUATAN_DAN_KELEMAHAN_ANGGOTA_TIM/BAWAHAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div16&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;17|SNG0014|UTAMA|YBS_DAPAT_MENGIDENTIFIKASI_KEKUATAN_DAN_KELEMAHAN_ANGGOTA_TIM/BAWAHAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='17|SNG0014|UTAMA|YBS_DAPAT_MENGIDENTIFIKASI_KEKUATAN_DAN_KELEMAHAN_ANGGOTA_TIM/BAWAHAN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div16']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
