<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SYAHKIMIKI NGOMAN_3SNG0014UTAMAYBS_DA_5b252b</name>
   <tag></tag>
   <elementGuidId>4383fe48-31e6-40dd-b572-b93d012b18f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='3|SNG0014|UTAMA|YBS_DAPAT_MENYELESAIKAN_KONFLIK_YANG_TERJADI_DI_UNIT_KERJA_DENGAN_EFEKTIF_DAN_OBYEKTIF'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3|SNG0014|UTAMA|YBS_DAPAT_MENYELESAIKAN_KONFLIK_YANG_TERJADI_DI_UNIT_KERJA_DENGAN_EFEKTIF_DAN_OBYEKTIF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>3|SNG0014|UTAMA|YBS_DAPAT_MENYELESAIKAN_KONFLIK_YANG_TERJADI_DI_UNIT_KERJA_DENGAN_EFEKTIF_DAN_OBYEKTIF</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div2&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;3|SNG0014|UTAMA|YBS_DAPAT_MENYELESAIKAN_KONFLIK_YANG_TERJADI_DI_UNIT_KERJA_DENGAN_EFEKTIF_DAN_OBYEKTIF&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='3|SNG0014|UTAMA|YBS_DAPAT_MENYELESAIKAN_KONFLIK_YANG_TERJADI_DI_UNIT_KERJA_DENGAN_EFEKTIF_DAN_OBYEKTIF'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div2']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
