<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioButton_Question_No_14</name>
   <tag></tag>
   <elementGuidId>6663a2b2-2391-46ce-8597-7eb28cefa5bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='14|SNG0014|UTAMA|YBS_BERSEDIA_MENERIMA_FEEDBACK_DARI_ORANG_LAIN_(ATASAN,_BAWAHAN_DAN_PARTNER_KERJA)'])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[14]/table/tbody/tr/td[6]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14|SNG0014|UTAMA|YBS_BERSEDIA_MENERIMA_FEEDBACK_DARI_ORANG_LAIN_(ATASAN,_BAWAHAN_DAN_PARTNER_KERJA)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>14|SNG0014|UTAMA|YBS_BERSEDIA_MENERIMA_FEEDBACK_DARI_ORANG_LAIN_(ATASAN,_BAWAHAN_DAN_PARTNER_KERJA)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[14]/table/tbody/tr/td[6]/input</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='14|SNG0014|UTAMA|YBS_BERSEDIA_MENERIMA_FEEDBACK_DARI_ORANG_LAIN_(ATASAN,_BAWAHAN_DAN_PARTNER_KERJA)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div13']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
