<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Textarea_Strength_Weakness</name>
   <tag></tag>
   <elementGuidId>83fa90f0-bfd1-438c-aedb-00bf6ededa48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='21|SNG0014|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_ATASAN:']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[21]/table/tbody/tr/td[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>21|SNG0014|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_ATASAN:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>21|SNG0014|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_ATASAN:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[21]/table/tbody/tr/td[2]/textarea</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='21|SNG0014|ESSAY|TULISKAN_STRENGTH_&amp;_WEAKNESS_MENGENAI_KARYAWAN_DIBAWAH_INI,_TERKAIT_PERANNYA_SEBAGAI_ATASAN:']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div20']/table/tbody/tr/td[2]/textarea</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
   </webElementXpaths>
</WebElementEntity>
