<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_18KEG2200UTAMASAYA_BER_1936ee</name>
   <tag></tag>
   <elementGuidId>30ebdfe9-3844-47e9-a84d-a350b9f53b93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='18|KEG2200|UTAMA|SAYA_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>18|KEG2200|UTAMA|SAYA_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>18|KEG2200|UTAMA|SAYA_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div17&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;18|KEG2200|UTAMA|SAYA_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='18|KEG2200|UTAMA|SAYA_BERUSAHA_MENGANTISIPASI_KEBUTUHAN_CUSTOMER_DENGAN_CARA_EFEKTIF_DAN_EFISIEN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div17']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
