<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_13KEG2200UTAMASAYA_TID_4f986b</name>
   <tag></tag>
   <elementGuidId>814b9f42-630b-4c41-b9da-9074347a141b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='13|KEG2200|UTAMA|SAYA_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13|KEG2200|UTAMA|SAYA_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>13|KEG2200|UTAMA|SAYA_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div12&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;13|KEG2200|UTAMA|SAYA_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='13|KEG2200|UTAMA|SAYA_TIDAK_PANTANG_MENYERAH_DAN_TUNTAS_MENYELESAIKAN_TANGGUNG_JAWAB_KETIKA_MENGHADAPI_KESULITAN'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div12']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
