<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_8KEG2200UTAMASAYA_MENU_544e6c</name>
   <tag></tag>
   <elementGuidId>aa3d9ac3-d747-4c63-8da9-1e30494475a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='8|KEG2200|UTAMA|SAYA_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8|KEG2200|UTAMA|SAYA_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>8|KEG2200|UTAMA|SAYA_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div7&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;8|KEG2200|UTAMA|SAYA_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='8|KEG2200|UTAMA|SAYA_MENUNJUKKAN_KOMITMEN_DAN_MEMBERIKAN_KONTRIBUSI_YANG_SIGNIFIKAN_UNTUK_TERCAPAI_NYA_TUJUAN_KELOMPOK'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div7']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
