<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_4KEG2200UTAMASAYA_MEMA_2cdaff</name>
   <tag></tag>
   <elementGuidId>252af7fd-0b4f-4380-85f2-4b19bee50df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='4|KEG2200|UTAMA|SAYA_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4|KEG2200|UTAMA|SAYA_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>4|KEG2200|UTAMA|SAYA_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div3&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;4|KEG2200|UTAMA|SAYA_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='4|KEG2200|UTAMA|SAYA_MEMAHAMI_ATAS_RESIKO_YANG_MUNCUL_DARI_PENYIMPANGAN_ATAU_PELANGGARAN_YANG_DIBUAT'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div3']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
