<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_3KEG2200UTAMASAYA_MEMI_67e805</name>
   <tag></tag>
   <elementGuidId>9e29d2ad-aaf9-4aee-a377-30313aa6e983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='3|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>3|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div2&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;3|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='3|KEG2200|UTAMA|SAYA_MEMILIKI_SEMANGAT_UNTUK_MENINGKATKAN_KEMAMPUAN_BAIK_MELALUI_BELAJAR_DARI_KESALAHAN_ATAU_BELAJAR_DARI_HAL_YANG_BARU'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div2']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
