<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_KELVIANDI GOUW_14KEG2200UTAMASAYA_MEM_1a9c36</name>
   <tag></tag>
   <elementGuidId>bc90d42f-e7b3-435e-90d5-de4d718b60dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='14|KEG2200|UTAMA|SAYA_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>14|KEG2200|UTAMA|SAYA_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>14|KEG2200|UTAMA|SAYA_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div13&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;14|KEG2200|UTAMA|SAYA_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='14|KEG2200|UTAMA|SAYA_MEMILIKI_KEPEDULIAN_DAN_SEMANGAT_KAIZEN_UNTUK_MENCAPAI_PRESTASI_LEBIH'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div13']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
