<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PRIHATINI SANDYA PUTRIE_1PSP0399PEMBU_07eaf5</name>
   <tag></tag>
   <elementGuidId>49b744cd-8639-46eb-af9c-58bfdf81798a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='1|PSP0399|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1|PSP0399|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1|PSP0399|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div0&quot;)/table[1]/tbody[1]/tr[5]/td[6]/input[@id=&quot;1|PSP0399|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='1|PSP0399|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div0']/table/tbody/tr[5]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
