<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FELICIA_1FEL1806PEMBUKASEBERAPA_SERIN_990d62</name>
   <tag></tag>
   <elementGuidId>a161cf5c-8183-41ae-8b58-be7777e669a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='1|FEL1806|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1|FEL1806|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>1|FEL1806|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div0&quot;)/table[1]/tbody[1]/tr[3]/td[4]/input[@id=&quot;1|FEL1806|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='1|FEL1806|PEMBUKA|SEBERAPA_SERING_ANDA_BERINTERAKSI_DENGAN_KARYAWAN_DI_BAWAH_INI'])[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div0']/table/tbody/tr[3]/td[4]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
   </webElementXpaths>
</WebElementEntity>
