<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PRIHATINI SANDYA PUTRIE_13PSP0399UTAM_246697</name>
   <tag></tag>
   <elementGuidId>6bbd8bc7-55c6-4bb7-b46d-8e79cb44e40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='13|PSP0399|UTAMA|YBS_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>13|PSP0399|UTAMA|YBS_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>13|PSP0399|UTAMA|YBS_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div12&quot;)/table[1]/tbody[1]/tr[5]/td[6]/input[@id=&quot;13|PSP0399|UTAMA|YBS_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='13|PSP0399|UTAMA|YBS_MEMILIKI_SEMANGAT__UNTUK_MENCAPAI_HASIL_TERBAIK_DALAM_PEKERJAANNYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div12']/table/tbody/tr[5]/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/table/tbody/tr[5]/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
