<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AZKA FADHLAN_20AFD1193UTAMAYBS_MELAKU_2f484d</name>
   <tag></tag>
   <elementGuidId>49444bf9-7a3f-48b0-8c2b-3f62bb3b3501</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='20|AFD1193|UTAMA|YBS_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>20|AFD1193|UTAMA|YBS_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>20|AFD1193|UTAMA|YBS_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div19&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;20|AFD1193|UTAMA|YBS_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='20|AFD1193|UTAMA|YBS_MELAKUKAN_MONITORING_UNTUK_MEMASTIKAN_TERJADINYA_PELAYANAN__TERBAIK_YANG_KONSISTEN_DI_UNIT_KERJA_NYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div19']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
