<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioButton_Question_No_02</name>
   <tag></tag>
   <elementGuidId>9d463595-45d4-4146-94b5-342217a99bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='2|RHD0584|UTAMA|SAYA_MENJAGA_KUALITAS_PEKERJAAN_(KERAPIAN,_KEAKURATAN,_KELENGKAPAN_DATA_)'])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;div1&quot;)/table[1]/tbody[1]/tr[1]/td[6]/input[@id=&quot;2|RHD0584|UTAMA|SAYA_MENJAGA_KUALITAS_PEKERJAAN_(KERAPIAN,_KEAKURATAN,_KELENGKAPAN_DATA_)&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2|RHD0584|UTAMA|SAYA_MENJAGA_KUALITAS_PEKERJAAN_(KERAPIAN,_KEAKURATAN,_KELENGKAPAN_DATA_)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>2|RHD0584|UTAMA|SAYA_MENJAGA_KUALITAS_PEKERJAAN_(KERAPIAN,_KEAKURATAN,_KELENGKAPAN_DATA_)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[2]/table/tbody/tr/td[6]/input</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='2|RHD0584|UTAMA|SAYA_MENJAGA_KUALITAS_PEKERJAAN_(KERAPIAN,_KEAKURATAN,_KELENGKAPAN_DATA_)'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div1']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
