<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RadioButton_Question_No_06</name>
   <tag></tag>
   <elementGuidId>95e86ccf-f03e-44d0-a142-aa697828132e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='6|SNG0014|UTAMA|YBS_MENDAPATKAN_KOMITMEN_DARI_BAWAHAN_UNTUK_MENDELIVER_PEKERJAAN_SESUAI_DENGAN_RENCANA_KERJA/ARAHAN_YANG_DIBERIKANNYA'])[5]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[6]/table/tbody/tr/td[6]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>6|SNG0014|UTAMA|YBS_MENDAPATKAN_KOMITMEN_DARI_BAWAHAN_UNTUK_MENDELIVER_PEKERJAAN_SESUAI_DENGAN_RENCANA_KERJA/ARAHAN_YANG_DIBERIKANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>6|SNG0014|UTAMA|YBS_MENDAPATKAN_KOMITMEN_DARI_BAWAHAN_UNTUK_MENDELIVER_PEKERJAAN_SESUAI_DENGAN_RENCANA_KERJA/ARAHAN_YANG_DIBERIKANNYA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>saveToLocalStorage(this)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/section[2]/div/div/div/form/div[3]/div/div/div/div[3]/div[6]/table/tbody/tr/td[6]/input</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='6|SNG0014|UTAMA|YBS_MENDAPATKAN_KOMITMEN_DARI_BAWAHAN_UNTUK_MENDELIVER_PEKERJAAN_SESUAI_DENGAN_RENCANA_KERJA/ARAHAN_YANG_DIBERIKANNYA'])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div5']/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/table/tbody/tr/td[6]/input</value>
   </webElementXpaths>
</WebElementEntity>
